# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diolog_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(310, 206)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.variety_name = QtWidgets.QLineEdit(Form)
        self.variety_name.setObjectName("variety_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.variety_name)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.degree_of_roast = QtWidgets.QLineEdit(Form)
        self.degree_of_roast.setObjectName("degree_of_roast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.degree_of_roast)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ground_or_in_grains = QtWidgets.QLineEdit(Form)
        self.ground_or_in_grains.setObjectName("ground_or_in_grains")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ground_or_in_grains)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.taste_description = QtWidgets.QLineEdit(Form)
        self.taste_description.setObjectName("taste_description")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.taste_description)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.price = QtWidgets.QLineEdit(Form)
        self.price.setObjectName("price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.packing_volume = QtWidgets.QLineEdit(Form)
        self.packing_volume.setObjectName("packing_volume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.packing_volume)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.run_ = QtWidgets.QPushButton(Form)
        self.run_.setObjectName("run_")
        self.horizontalLayout.addWidget(self.run_)
        self.close_ = QtWidgets.QPushButton(Form)
        self.close_.setObjectName("close_")
        self.horizontalLayout.addWidget(self.close_)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название сорта"))
        self.label_3.setText(_translate("Form", "Степень обжарки"))
        self.label_4.setText(_translate("Form", "Молотый/в зернах"))
        self.label_2.setText(_translate("Form", "Описание вкуса"))
        self.label_5.setText(_translate("Form", "Цена (руб.)"))
        self.label_6.setText(_translate("Form", "Объем упаковки (г.)"))
        self.run_.setText(_translate("Form", "OK"))
        self.close_.setText(_translate("Form", "Отмена"))
